In [4]:
import pandas as pd
import numpy as np


In [21]:
header = ['user1', 'user2', 'rating']
df = pd.read_csv('ratings.dat', sep=' ', names=header)
df

user1  user2  rating
0       1      2       1
1       1      3       1
2       1      5       1
3       2      1       1
4       2      3       1
5       3      1       1
6       3      5       1
7       4      1      -1
8       4      2       1
9       4      5       1
10      5      3      -1
11      5      2       1
12      1      7       1
13      7      1       1
14      2      7       1
15      7      2       1
16      2      8       1
17      8      2       1
18      1      8       1
19      1      9       1
20      9      1       1
21      2      9       1
22      9      2       1

In [22]:
df.pivot(index='user1', columns='user2', values='rating')

user2    1    2    3    5    7    8    9
user1                                   
1      NaN  1.0  1.0  1.0  1.0  1.0  1.0
2      1.0  NaN  1.0  NaN  1.0  1.0  1.0
3      1.0  NaN  NaN  1.0  NaN  NaN  NaN
4     -1.0  1.0  NaN  1.0  NaN  NaN  NaN
5      NaN  1.0 -1.0  NaN  NaN  NaN  NaN
7      1.0  1.0  NaN  NaN  NaN  NaN  NaN
8      NaN  1.0  NaN  NaN  NaN  NaN  NaN
9      1.0  1.0  NaN  NaN  NaN  NaN  NaN

In [23]:
x = df.pivot(index='user1', columns='user2', values='rating')

In [24]:
#type(x)

#type(df)

In [25]:
x.loc[1,1]

nan

In [26]:
x.loc[1,5]

1.0

In [27]:
similar_list = pd.Series([1,2])
for user in similar_list:
    print(user)

1
2


In [28]:
candidate_list = np.empty(0, dtype=int)

type(candidate_list)


numpy.ndarray

In [29]:
for user in similar_list:
    if user in x.index.values and user in x.columns.values:
        for row in x.index.values:
            if x.loc[row, user] == 1 and row in x.columns.values and x.loc[user, row] == 1:
                #print(user[1], row)
                candidate_list = np.append(candidate_list, row)            

In [30]:
candidate_list

array([2, 3, 7, 9, 1, 7, 8, 9])

In [31]:
candidate_list = np.unique(candidate_list)
candidate_list

array([1, 2, 3, 7, 8, 9])

In [32]:
def filter_candidate(candidates):
    index_list = []
    for user in similar_list.iteritems():
        if user[1] in candidates:
            index = np.argwhere(candidates==user[1])
            index_list.append(index)
    return np.delete(candidates, index_list)

candidate_list = filter_candidate(candidate_list)
candidate_list




array([3, 7, 8, 9])

In [33]:
cols = ['pos', 'neg', 'score']
scores_df = pd.DataFrame(0, index=candidate_list, columns=cols)
scores_df


pos  neg  score
3    0    0      0
7    0    0      0
8    0    0      0
9    0    0      0

In [34]:
for cand in candidate_list:
    for user in similar_list:
        if x.loc[cand, user] == 1 and x.loc[user, cand]==1:
            temp = scores_df.at[cand,'pos']
            scores_df.set_value(cand, 'pos', temp+1)
        elif (x.loc[cand, user] == 1 and x.loc[user, cand] == -1) or (x.loc[user, cand]==1 and x.loc[cand,user] ==-1):
            temp = scores_df.at[cand,'neg']
            scores_df.set_value(cand, 'neg', temp+1)
    temp2 = scores_df.at[cand,'pos'] + scores_df.at[cand,'neg']
    scores_df.set_value(cand, 'score', temp2)

In [19]:
scores_df

pos  neg  score
3    1    0      1
7    2    0      2
8    1    0      1
9    2    0      2

In [35]:
result = scores_df.sort_values('score', ascending=0)
result


pos  neg  score
7    2    0      2
9    2    0      2
3    1    0      1
8    1    0      1

## 