In [1]:
import pandas as pd

In [2]:
header_profile = ['uid', 'age1', 'height1', 'religion1', 'caste1', 'education1', 'occupation1', 'income1', 'body1', 'complexion1', 'diet1', 'smoke1', 'drink1', 'age2', 'height2', 'religion2', 'caste2', 'education2', 'occupation2', 'income2', 'body2', 'complexion2', 'diet2', 'smoke2', 'drink2']
weights_profile = ['uid', 'age_wt', 'heig_wt', 'edu_wt', 'inco_wt', 'body_wt', 'comlex_wt']

In [3]:
male_prof_df = pd.read_csv('male.dat', sep=' ', names=header_profile, index_col=False)
female_prof_df = pd.read_csv('female.dat', sep=' ', names=header_profile, index_col=False)


In [4]:
male_prof_df = male_prof_df.set_index('uid')
female_prof_df = female_prof_df.set_index('uid')



In [5]:
male_weig_df = pd.read_csv('male_weights.dat', sep=' ', names=weights_profile, index_col=False)
female_weig_df = pd.read_csv('female_weights.dat', sep=' ', names=weights_profile, index_col=False)


In [6]:
male_weig_df = male_weig_df.set_index('uid')
female_weig_df = female_weig_df.set_index('uid')

In [7]:
female_weig_df

age_wt  heig_wt  edu_wt  inco_wt  body_wt  comlex_wt
uid                                                      
1         1        2       3        4        5          6
2         1        2       3        4        5          6
3         1        2       3        4        5          6
4         1        2       3        4        5          6
5         1        2       3        4        5          6

In [8]:
male_prof_df

age1  height1  religion1  caste1  education1  occupation1  income1  \
uid                                                                       
6       1        1          1       1           1            1        1   
7       2        2          2       2           2            2        2   
8       3        3          3       3           3            3        3   
9       4        4          4       4           4            4        4   
10      4        4          4       4           4            4        4   
11      1        1          1       1           1            1        1   

     body1  complexion1  diet1   ...    religion2  caste2  education2  \
uid                              ...                                    
6        1            1      1   ...            1       1           1   
7        2            2      2   ...            2       2           2   
8        3            3      3   ...            3       3           3   
9        4            4      4   ...            4       4           4   
10       4            4      4   ...            4       4           4   
11       1            1      1   ...            1       1           3   

     occupation2  income2  body2  complexion2  diet2  smoke2  drink2  
uid                                                                   
6              1        1      1            1      1       1       1  
7              2        2      2            2      2       2       2  
8              3        3      3            3      3       3       3  
9              4        4      4            4      4       4       4  
10             4        4      4            4      4       4       4  
11             2        5      2            2      1       1       1  

[6 rows x 24 columns]

In [9]:
male_prof_weig_df = pd.concat([male_prof_df, male_weig_df], axis=1)

In [10]:
male_prof_weig_df

age1  height1  religion1  caste1  education1  occupation1  income1  \
uid                                                                       
6       1        1          1       1           1            1        1   
7       2        2          2       2           2            2        2   
8       3        3          3       3           3            3        3   
9       4        4          4       4           4            4        4   
10      4        4          4       4           4            4        4   
11      1        1          1       1           1            1        1   

     body1  complexion1  diet1    ...      complexion2  diet2  smoke2  drink2  \
uid                               ...                                           
6        1            1      1    ...                1      1       1       1   
7        2            2      2    ...                2      2       2       2   
8        3            3      3    ...                3      3       3       3   
9        4            4      4    ...                4      4       4       4   
10       4            4      4    ...                4      4       4       4   
11       1            1      1    ...                2      1       1       1   

     age_wt  heig_wt  edu_wt  inco_wt  body_wt  comlex_wt  
uid                                                        
6       1.0      2.0     3.0      4.0      5.0        6.0  
7       1.0      2.0     3.0      4.0      5.0        6.0  
8       1.0      2.0     3.0      4.0      5.0        6.0  
9       1.0      2.0     3.0      4.0      5.0        6.0  
10      NaN      NaN     NaN      NaN      NaN        NaN  
11     10.0     10.0    10.0     10.0     10.0       10.0  

[6 rows x 30 columns]

In [11]:
female_prof_weig_df = pd.concat([female_prof_df, female_weig_df], axis=1)

In [12]:
female_prof_weig_df

age1  height1  religion1  caste1  education1  occupation1  income1  \
uid                                                                       
1       1        1          1       1           1            1        1   
2       2        2          2       2           2            2        2   
3       3        3          3       3           3            3        3   
4       4        4          4       4           4            4        4   
5       4        4          4       4           4            4        4   
21      4        6          1       1           5            2        3   
22      3        5          1       1           6            2        4   
23      6        3          1       1           6            2        8   
24      2        2          1       1           2            2        5   
25      4        4          1       1           4            2        2   

     body1  complexion1  diet1    ...      complexion2  diet2  smoke2  drink2  \
uid                               ...                                           
1        1            1      1    ...                1      1       1       1   
2        2            2      2    ...                2      2       2       2   
3        3            3      3    ...                3      3       3       3   
4        4            4      4    ...                4      4       4       4   
5        4            4      4    ...                4      4       4       4   
21       2            1      1    ...                2      2       2       2   
22       1            1      1    ...                2      2       2       2   
23       3            2      1    ...                2      2       2       2   
24       3            3      1    ...                2      2       2       2   
25       4            4      1    ...                2      2       2       2   

     age_wt  heig_wt  edu_wt  inco_wt  body_wt  comlex_wt  
uid                                                        
1       1.0      2.0     3.0      4.0      5.0        6.0  
2       1.0      2.0     3.0      4.0      5.0        6.0  
3       1.0      2.0     3.0      4.0      5.0        6.0  
4       1.0      2.0     3.0      4.0      5.0        6.0  
5       1.0      2.0     3.0      4.0      5.0        6.0  
21      NaN      NaN     NaN      NaN      NaN        NaN  
22      NaN      NaN     NaN      NaN      NaN        NaN  
23      NaN      NaN     NaN      NaN      NaN        NaN  
24      NaN      NaN     NaN      NaN      NaN        NaN  
25      NaN      NaN     NaN      NaN      NaN        NaN  

[10 rows x 30 columns]

In [20]:
from main_recommender import *

In [21]:
def give_recommendations(user_id):
    if user_id in male_prof_df.index:
        prim_user_ref = male_prof_weig_df.loc[user_id]
        prim_user = User(int(user_id), int(prim_user_ref.age1), int(prim_user_ref.height1), int(prim_user_ref.religion1), int(prim_user_ref.caste1), int(prim_user_ref.education1), int(prim_user_ref.occupation1), int(prim_user_ref.income1), int(prim_user_ref.body1), int(prim_user_ref.complexion1), int(prim_user_ref.diet1), int(prim_user_ref.smoke1), int(prim_user_ref.drink1), int(prim_user_ref.age2), int(prim_user_ref.height2), int(prim_user_ref.religion2), int(prim_user_ref.caste2), int(prim_user_ref.education2), int(prim_user_ref.occupation2), int(prim_user_ref.income2), int(prim_user_ref.body2), int(prim_user_ref.complexion2), int(prim_user_ref.diet2), int(prim_user_ref.smoke2), int(prim_user_ref.drink2), [prim_user_ref.age_wt, prim_user_ref.heig_wt, prim_user_ref.edu_wt, prim_user_ref.inco_wt, prim_user_ref.body_wt, prim_user_ref.comlex_wt]) 
        for user_id2 in female_prof_df.index:
            sec_user_ref = female_prof_weig_df.loc[user_id2]
            sec_user = User(int(user_id2), int(sec_user_ref.age1), int(sec_user_ref.height1), int(sec_user_ref.religion1), int(sec_user_ref.caste1), int(sec_user_ref.education1), int(sec_user_ref.occupation1), int(sec_user_ref.income1), int(sec_user_ref.body1), int(sec_user_ref.complexion1), int(sec_user_ref.diet1), int(sec_user_ref.smoke1), int(sec_user_ref.drink1), int(sec_user_ref.age2), int(sec_user_ref.height2), int(sec_user_ref.religion2), int(sec_user_ref.caste2), int(sec_user_ref.education2), int(sec_user_ref.occupation2), int(sec_user_ref.income2), int(sec_user_ref.body2), int(sec_user_ref.complexion2), int(sec_user_ref.diet2), int(sec_user_ref.smoke2), int(sec_user_ref.drink2), [sec_user_ref.age_wt, sec_user_ref.heig_wt, sec_user_ref.edu_wt, sec_user_ref.inco_wt, sec_user_ref.body_wt, sec_user_ref.comlex_wt]) 
            #return prim_user, sec_user
            CrispCheck(prim_user, sec_user)
        sorted_dict = sorted(prim_user.recommendations_scores.items(), key=lambda x: x[1], reverse=True)
        print(sorted_dict)

In [22]:
give_recommendations(11)


[(21, 49.299999999999997), (24, 48.399999999999999), (22, 46.450000000000003), (23, 45.200000000000003), (25, 44.649999999999999)]


In [34]:
#from scipy.spatial.distance import cosine
#from sklearn.metrics.pairwise import cosine_similarity



In [32]:
#df = male_prof_df.iloc[:, 0:12]

In [33]:
#df

age1  height1  religion1  caste1  education1  occupation1  income1  \
uid                                                                       
6       6        6          6       6           6            6        6   
7       7        7          7       7           7            7        7   
8       8        8          8       8           8            8        8   
9       9        9          9       9           9            9        9   

     body1  complexion1  diet1  smoke1  drink1  
uid                                             
6        6            6      6       6       6  
7        7            7      7       7       7  
8        8            8      8       8       8  
9        9            9      9       9       9

In [35]:
#cosine_similarity(df)


array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [36]:
#from scipy.spatial.distance import pdist


In [38]:
#x = pdist(df, metric='cosine')

In [39]:
#x

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [40]:
#df

age1  height1  religion1  caste1  education1  occupation1  income1  \
uid                                                                       
6       6        6          6       6           6            6        6   
7       7        7          7       7           7            7        7   
8       8        8          8       8           8            8        8   
9       9        9          9       9           9            9        9   

     body1  complexion1  diet1  smoke1  drink1  
uid                                             
6        6            6      6       6       6  
7        7            7      7       7       7  
8        8            8      8       8       8  
9        9            9      9       9       9

In [46]:
#t = df.values


In [47]:
#t.shape

(4, 12)

In [48]:
#pdist(t, metric='cosine')

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [105]:
ut = male_prof_df.loc[6]

In [106]:
ut.age1

1

In [107]:
type(ut.age1)

numpy.int64

In [109]:
ut2 = int(ut.age1)

In [110]:
type(ut2)

int